[package]
name = "address"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = { workspace = true }
windows = { workspace = true, features = [
    "Win32_System_SystemServices",
    "Win32_System_Threading",
    "Win32_System_ProcessStatus",
] }
